---
title: "Data Rectangling"
author: "Muhammad Aswan Syahputra"
date: "8/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{bash scrape-instagram, eval = FALSE}
instagram-scraper tirtoid -m 20 --comments --media-types none
```

```{r load-packages}
library(jsonlite)
library(listviewer)
library(tidyverse)
```

```{r inspect-json}
my_json <- fromJSON("tirtoid/tirtoid.json")
jsonedit(my_json)
```

```{r transform-json}
transformed_json <- 
  my_json %>% 
  pluck(1) %>% 
  jsonlite::flatten() %>%
  transpose() %>%
  enframe(name = "id", value = "post")
transformed_json
```

```{r map}
transformed_json %>%
  mutate(
    post_time = map(post, "taken_at_timestamp"),
    is_video = map(post, "is_video"),
    caption = map(post, list(
      "edge_media_to_caption.edges", "node", "text"
    )),
    tags = map(post, "tags"),
    video_view = map(post, "video_view_count"),
    media_like = map(post, "edge_media_preview_like.count"),
    comments_username = map(post, list("comments.data", "owner", "username")),
    comments_time = map(post, list("comments.data", "created_at")),
    comments_text = map(post, list("comments.data", "text"))
  )
```

```{r map-variant}
transformed_json %>%
  mutate(
    post_time = map_int(post, "taken_at_timestamp"),
    is_video = map_lgl(post, "is_video"),
    caption = map_chr(post, list(
      "edge_media_to_caption.edges", "node", "text"
    )),
    tags = map(post, "tags"),
    video_view = map_int(post, "video_view_count"),
    media_like = map_int(post, "edge_media_preview_like.count"),
    comments_username = map(post, list("comments.data", "owner", "username")),
    comments_time = map(post, list("comments.data", "created_at")),
    comments_text = map(post, list("comments.data", "text"))
  )
```

```{r define-smart-map}
#' Smart extraction of elements from list
#'
#' Extract and possibly flatten the output of elements extraction automatically.
#' @param .x A list or atomic vectors
#' @param what An elemet of list to be extracted
#' @return A list or possibly an atomic vector
#' @importFrom purrr map
#' @export
smart_map <- function(.x, what) {
  res <- map(.x, what, .default = NA)
  if (all(sapply(res, length) == 1)) {
    res <- unlist(res)
  }
  return(res)
}
```

```{r smart-map}
transformed_json %>% 
  mutate(
    post_time = smart_map(post, "taken_at_timestamp"),
    is_video = smart_map(post, "is_video"),
    caption = smart_map(post, list(
      "edge_media_to_caption.edges", "node", "text"
    )),
    tags = smart_map(post, "tags"),
    video_view = smart_map(post, "video_view_count"),
    media_like = smart_map(post, "edge_media_preview_like.count"),
    comments_username = smart_map(post, list("comments.data", "owner", "username")),
    comments_time = smart_map(post, list("comments.data", "created_at")),
    comments_text = smart_map(post, list("comments.data", "text"))
  )
```

```{r unnest-comments}
tirtoid_comments <- 
  transformed_json %>%
  mutate(
    post_time = smart_map(post, "taken_at_timestamp"),
    is_video = smart_map(post, "is_video"),
    caption = smart_map(post, list(
      "edge_media_to_caption.edges", "node", "text"
    )),
    tags = smart_map(post, "tags"),
    video_view = smart_map(post, "video_view_count"),
    media_like = smart_map(post, "edge_media_preview_like.count"),
    comments_username = smart_map(post, list("comments.data", "owner", "username")),
    comments_time = smart_map(post, list("comments.data", "created_at")),
    comments_text = smart_map(post, list("comments.data", "text"))
  ) %>% 
  select(-post) %>% 
  mutate(
    tags = map_chr(tags, paste, collapse = ", ")
  ) %>% 
  unnest()
```

```{r}
tirtoid_comments %>% 
  mutate_at(vars(ends_with("time")), ~as.POSIXct(.x, origin  = "1970-01-01")) %>% 
  mutate_if(is.numeric, ~ .x %>% str_remove_all("\\n") %>% str_trim())
```
